### ISSUE TITLE
Spuštění programu poškozuje lokální hosts soubor

### ISSUE THREAD

**Issue by sasule** [JachyHm/MapyCZforTS#1]
Po spuštění programu dojde k tomu, že program vyhodí z hosts souboru např.:
192.168.1.11 mujserver
EDIT:
Vyhodí:
192.168.1.11 mujhosting.czx 
192.168.1.11 www.mujhosting.czx
Ale ponechá:
192.168.1.11      mujhosting2.czx 
192.168.1.11      www.mujhosting2.czx

Případně vyhodí IP adresu 0.0.0.0 fake.server.org.
Program by měl pouze do host připsal ailias na google mapy.

**Comment by JachyHm** [comment]
Neřešeno, viz. nová verze MapyCZforTS2.
